name: markdown-link-check

on:
  workflow_dispatch:
  push:
    branches:
    #- main
    - add_build_action
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:

  markdown-link-check:
    name: Check markdown links
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: gaurav-nelson/github-action-markdown-link-check@v1